In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

# import csv's

median_income = pd.read_csv("./Raw Data Files/Median Income.csv", encoding='latin1')
median_home_value_acs = pd.read_csv("./Raw Data Files/Median Home Value - ACS.csv", encoding='latin1')
zillow_home_value = pd.read_csv("./Raw Data Files/Zillow Home Value.csv", encoding='latin1')
zillow_bottom_tier = pd.read_csv("./Raw Data Files/Zillow Bottom Tier Home Value.csv", encoding='latin1')
zillow_top_tier = pd.read_csv("./Raw Data Files/Zillow Top Tier Home Value.csv", encoding='latin1')

In [2]:
# refine housing and income data by selecting relevant columns and renaming columns

median_income = median_income[["Geography","County","state","Mean income (dollars); Estimate; All households"]]
median_income = median_income.rename(columns={"state":"State","Mean income (dollars); Estimate; All households":"Median Income"})

median_home_value_acs = median_home_value_acs[["Geography","Estimate; Median value (dollars)"]]
median_home_value_acs = median_home_value_acs.rename(columns={"Estimate; Median value (dollars)":"ACS Home Value"})

zillow_home_value = zillow_home_value[["geography","Zhvi"]]
zillow_home_value = zillow_home_value.rename(columns={"geography":"Geography","Zhvi":"Zillow Home Value"})

zillow_bottom_tier = zillow_bottom_tier[["Geography","2018-12"]]
zillow_bottom_tier = zillow_bottom_tier.rename(columns={"2018-12":"Zillow Bottom Tier Home Value"})

zillow_top_tier = zillow_top_tier[["Geography","2018-12"]]
zillow_top_tier = zillow_top_tier.rename(columns={"2018-12":"Zillow Top Tier Home Value"})

# create a csv for the county and state data

output_data = median_income[["Geography","County","State"]]

output_data.to_csv("./Interim Data Files/State and County Info.csv", index=False, header=True)

In [3]:
# merge data into one table
data_table = pd.merge(median_income,median_home_value_acs,how='left',on='Geography')
data_table = pd.merge(data_table,zillow_home_value,how='left', on='Geography')
data_table = pd.merge(data_table,zillow_bottom_tier,how='left', on='Geography')
data_table = pd.merge(data_table,zillow_top_tier,how='left', on='Geography')

In [4]:
data_table.head(100)

,Geography,County,State,Median Income,ACS Home Value,Zillow Home Value,Zillow Bottom Tier Home Value,Zillow Top Tier Home Value
0,"Autauga County, Alabama",Autauga County,Alabama,72110,143000,159300.0,NaN,235400.0
1,"Baldwin County, Alabama",Baldwin County,Alabama,73061,182000,213600.0,134800.0,384900.0
2,"Barbour County, Alabama",Barbour County,Alabama,45445,89300,NaN,NaN,NaN
3,"Bibb County, Alabama",Bibb County,Alabama,61099,105500,NaN,NaN,NaN
4,"Blount County, Alabama",Blount County,Alabama,58974,122200,140600.0,82700.0,228600.0
5,"Bullock County, Alabama",Bullock County,Alabama,42317,66800,NaN,NaN,NaN
6,"Butler County, Alabama",Butler County,Alabama,47812,88800,NaN,NaN,NaN
7,"Calhoun County, Alabama",Calhoun County,Alabama,58788,110100,NaN,NaN,NaN
8,"Chambers County, Alabama",Chambers County,Alabama,51434,86400,NaN,NaN,NaN
9,"Cherokee County, Alabama",Cherokee County,Alabama,54671,116300,117300.0,55100.0,195100.0
10,"Chilton County, Alabama",Chilton County,Alabama,59036,98600,118400.0,54900.0,205100.0
11,"Choctaw County, Alabama",Choctaw County,Alabama,48466,69000,NaN,NaN,NaN
12,"Clarke County, Alabama",Clarke County,Alabama,50851,93500,NaN,NaN,NaN
13,"Clay County, Alabama",Clay County,Alabama,51364,89300,NaN,NaN,NaN
14,"Cleburne County, Alabama",Cleburne County,Alabama,51607,111800,NaN,NaN,NaN
15,"Coffee County, Alabama",Coffee County,Alabama,65863,147800,114400.0,NaN,228800.0
16,"Colbert County, Alabama",Colbert County,Alabama,56372,108500,96500.0,50600.0,186200.0
17,"Conecuh County, Alabama",Conecuh County,Alabama,39554,76100,NaN,NaN,NaN
18,"Coosa County, Alabama",Coosa County,Alabama,48059,87300,NaN,NaN,NaN
19,"Covington County, Alabama",Covington County,Alabama,53372,96200,NaN,NaN,NaN
20,"Crenshaw County, Alabama",Crenshaw County,Alabama,52395,76800,NaN,NaN,NaN
21,"Cullman County, Alabama",Cullman County,Alabama,55135,121900,NaN,NaN,NaN
22,"Dale County, Alabama",Dale County,Alabama,57087,108000,NaN,NaN,NaN
23,"Dallas County, Alabama",Dallas County,Alabama,44023,80800,NaN,NaN,NaN
24,"DeKalb County, Alabama",DeKalb County,Alabama,52462,102900,NaN,NaN,NaN
25,"Elmore County, Alabama",Elmore County,Alabama,71437,155300,163300.0,88500.0,278600.0
26,"Escambia County, Alabama",Escambia County,Alabama,48727,94500,NaN,NaN,NaN
27,"Etowah County, Alabama",Etowah County,Alabama,55354,105100,103100.0,NaN,175600.0
28,"Fayette County, Alabama",Fayette County,Alabama,50889,83200,NaN,NaN,NaN
29,"Franklin County, Alabama",Franklin County,Alabama,50902,87600,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
70,"Bethel Census Area, Alaska",Bethel Census Area,Alaska,67827,152600,NaN,NaN,NaN
71,"Bristol Bay Borough, Alaska",Bristol Bay Borough,Alaska,93172,186700,NaN,NaN,NaN
72,"Denali Borough, Alaska",Denali Borough,Alaska,90822,224200,NaN,NaN,NaN
73,"Dillingham Census Area, Alaska",Dillingham Census Area,Alaska,72392,189500,NaN,NaN,NaN
74,"Fairbanks North Star Borough, Alaska",Fairbanks North Star Borough,Alaska,91968,230600,253800.0,166000.0,347200.0
75,"Haines Borough, Alaska",Haines Borough,Alaska,84311,243100,NaN,NaN,NaN
76,"Hoonah-Angoon Census Area, Alaska",Hoonah-Angoon Census Area,Alaska,72020,226800,NaN,NaN,NaN
77,"Juneau City and Borough, Alaska",Juneau City and Borough,Alaska,106849,343100,NaN,NaN,NaN
78,"Kenai Peninsula Borough, Alaska",Kenai Peninsula Borough,Alaska,82690,234600,245900.0,175100.0,361600.0
79,"Ketchikan Gateway Borough, Alaska",Ketchikan Gateway Borough,Alaska,83221,265700,286800.0,185800.0,418700.0
80,"Kodiak Island Borough, Alaska",Kodiak Island Borough,Alaska,88572,267700,334100.0,234200.0,451000.0
81,"Kusilvak Census Area, Alaska",Kusilvak Census Area,Alaska,47396,88600,NaN,NaN,NaN
82,"Lake and Peninsula Borough, Alaska",Lake and Peninsula Borough,Alaska,62034,118500,NaN,NaN,NaN
83,"Matanuska-Susitna Borough, Alaska",Matanuska-Susitna Borough,Alaska,88473,235600,NaN,NaN,NaN
84,"Nome Census Area, Alaska",Nome Census Area,Alaska,69905,143000,NaN,NaN,NaN
85,"North Slope Borough, Alaska",North Slope Borough,Alaska,94748,153900,NaN,NaN,NaN
86,"Northwest Arctic Borough, Alaska",Northwest Arctic Borough,Alaska,79496,145800,NaN,NaN,NaN
87,"Petersburg Borough, Alaska",Petersburg Borough,Alaska,83850,205000,NaN,NaN,NaN
88,"Prince of Wales-Hyder Census Area, Alaska",Prince of Wales-Hyder Census Area,Alaska,65973,169100,NaN,NaN,NaN
89,"Sitka City and Borough, Alaska",Sitka City and Borough,Alaska,84007,350900,NaN,NaN,NaN
90,"Skagway Municipality, Alaska",Skagway Municipality,Alaska,81260,293800,NaN,NaN,NaN
91,"Southeast Fairbanks Census Area, Alaska",Southeast Fairbanks Census Area,Alaska,74772,191700,NaN,NaN,NaN
92,"Valdez-Cordova Census Area, Alaska",Valdez-Cordova Census Area,Alaska,99003,252200,NaN,NaN,NaN
93,"Wrangell City and Borough, Alaska",Wrangell City and Borough,Alaska,67544,194000,NaN,NaN,NaN
94,"Yakutat City and Borough, Alaska",Yakutat City and Borough,Alaska,70348,185000,NaN,NaN,NaN
95,"Yukon-Koyukuk Census Area, Alaska",Yukon-Koyukuk Census Area,Alaska,51731,80600,NaN,NaN,NaN
96,"Apache County, Arizona",Apache County,Arizona,43510,72800,159500.0,92000.0,263600.0
97,"Cochise County, Arizona",Cochise County,Arizona,61398,144400,143400.0,74200.0,237800.0
98,"Coconino County, Arizona",Coconino County,Arizona,72255,241400,353200.0,231300.0,545700.0
99,"Gila County, Arizona",Gila County,Arizona,54167,153600,206700.0,NaN,345000.0

In [5]:
data_table.to_csv("./Input Files/Income and Housing Data.csv", index=False, header=True)